# Generated by Django 3.2.25 on 2024-05-10 22:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='logos')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('fee', models.FloatField()),
                ('description', models.TextField(max_length=10000)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ref_no', models.CharField(blank=True, max_length=200, null=True)),
                ('full_notice', models.FileField(blank=True, null=True, upload_to='adverts')),
                ('bidding_doc', models.FileField(blank=True, null=True, upload_to='outgoing_bids')),
                ('preview_biddoc', models.FileField(blank=True, null=True, upload_to='preview_zips')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('bid', models.FileField(blank=True, null=True, upload_to='bids', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar'])])),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('files_attached', models.CharField(blank=True, max_length=10, null=True)),
                ('submission_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biddingApp.applicant')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biddingApp.notice')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_ref', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biddingApp.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='message_files/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('letter', models.FileField(upload_to='letters')),
                ('apply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bid_document', models.FileField(blank=True, null=True, upload_to='')),
                ('application_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biddingApp.applicant')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biddingApp.notice')),
            ],
        ),
    ]
